name: TypeScript x InvisiRisk

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@test
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}

      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Build or Tests
        run: bun run build # or 'bun run test', adjust to your script

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@test
        with:
          cleanup: "true"
